spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/users/**
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/**
            - id: bus-service
              uri: lb://BUS-SERVICE
              predicates:
                - Path=/buses/**
            - id: reservation-service
              uri: lb://RESERVATION-SERVICE
              predicates:
                - Path=/reservations/**
